### ISSUE TITLE
Failed to compile in FreeBSD 10.3

### ISSUE THREAD

**Issue by dram** [trealla-lang/trealla#97]
Compling Trealla in FreeBSD 10.3 failed with following error:

```
...
cc -o tpl tpl.o src/trealla.o src/parser.o src/bifs_iso.o src/jela.o  src/list.o src/print.o src/skiplist.o src/utf8.o  src/history.o src/daemon.o src/base64.o src/bifs_sys.o src/bifs_http.o  src/jsonq.o src/bifs_net.o src/bifs_proc.o  src/network.o src/skipbuck.o src/thread.o src/uncle.o  src/uuid.o src/xmlq.o src/bifs_dbs.o src/library.o  src/auth.o src/blog.o src/dict.o  src/http_client.o src/smtp_client.o  -lm -lssl -lcrypto -pthread
src/trealla.o: In function `trealla_readline':
src/trealla.c:(.text+0x77d): undefined reference to `fgetc_unlocked'
src/trealla.c:(.text+0x7b1): undefined reference to `fgetc_unlocked'
src/bifs_iso.o: In function `bif_iso_get_byte':
src/bifs_iso.c:(.text+0x10263): undefined reference to `fgetc_unlocked'
src/bifs_iso.o: In function `bif_iso_get_byte2':
src/bifs_iso.c:(.text+0x1085d): undefined reference to `fgetc_unlocked'
src/bifs_iso.o: In function `bif_iso_peek_code':
src/bifs_iso.c:(.text+0x10bd3): undefined reference to `fgetc_unlocked'
src/bifs_iso.o:src/bifs_iso.c:(.text+0x10d37): more undefined references to `fgetc_unlocked' follow
cc: error: linker command failed with exit code 1 (use -v to see invocation)
*** Error code 1

Stop.
...
```

**Comment by dram** [comment]
It compiled successfully now, thanks!
