### ISSUE TITLE
Failed to compile in FreeBSD 10.3

### ISSUE THREAD

**Issue by dram** [trealla-lang/trealla#102]
Compiling Trealla in FreeBSD 10.3 failed with following error:

```
cc -Isrc -O3  -Wall -D_DEFAULT_SOURCE -D_BSD_SOURCE -Wwrite-strings -I/usr/local/include -DUSE_SSL=1 -pthread -c src/trealla.c -o src/trealla.o
In file included from src/trealla.c:26:
In file included from src/bifs.h:4:
src/internal.h:202:8: error: redefinition of 'stream_'
struct stream_
       ^
src/internal.h:190:8: note: previous definition is here
struct stream_
       ^
1 error generated.
*** Error code 1
```

**Comment by infradig** [comment]
It was the master branch, on Linux with GCC as well. Devel was fine.

**Comment by dram** [comment]
Yes, fix confirmed.
